name: Nikto 
on: [push]
jobs:
  nikto-scan:
    runs-on: ubuntu-latest
    #needs: deployment
    steps:
      - name: Updated Packages
        run: sudo apt-get update
      
      - name: Install Nikto
        run: sudo apt install nikto
      - name: Scan the Domain
        run: nikto -h ${{ secrets.SURGE_DOMAIN }} -Format json -o nikto_scan_report.json
    

      - name: Upload the Scan Report
        uses: actions/upload-artifact@v2
        with:
          name: nikto_scan_report-results
          path: nikto_scan_report.json
        if: always()    

